version: "3.7"

services:
  runner:
    container_name: github-runner
    image: ewrogers/github-runner
    build: .
    environment:
      RUNNER_NAME: ${RUNNER_NAME}
      # RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
      RUNNER_LABELS: ${RUNNER_LABELS}
      RUNNER_WORK_DIRECTORY: /tmp/github-runner/_work
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /tmp/github-runner:/tmp/github-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
