version: "3.7"

services:
  runner:
    container_name: github-runner
    image: ewrogers/github-runner
    build: .
# If you want resource limits, uncomment this and adjust as necessary
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 4G
    environment:
      RUNNER_NAME: "${RUNNER_NAME}"
      # RUNNER_REPOSITORY_URL: "${RUNNER_REPOSITORY_URL}"
      RUNNER_ORGANIZATION_URL: "${RUNNER_ORGANIZATION_URL}"
      RUNNER_LABELS: "${RUNNER_LABELS}"
      GITHUB_ACCESS_TOKEN: "${GITHUB_ACCESS_TOKEN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
